version: "3.9"

services:
  # jardinconecta-api:
  #   build:
  #     context: ./JardinConecta
  #     dockerfile: Dockerfile
  #   container_name: jardinconecta-api
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
  #     ConnectionStrings__Default: "Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
  #     MongoDb__ConnectionString: "mongodb://mongo:27017"
  #     MongoDb__Database: ${MONGO_DB}
  #     Jwt__Key: ${JWT_KEY}
  #   ports:
  #     - "${API_PORT}:8080"
  #   restart: always

  postgres:
    image: postgres:16
    container_name: jardinconecta-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  mongo:
    image: mongo:7
    container_name: jardinconecta-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  postgres_data:
  mongo_data: